version: '2'
volumes:
        unifi-data:
services:
        unifi:
                build: ./unifi
                ports:
                        - "10001:10001/udp" # AP discovery 
                        - "3478:3478/udp" # STUN
                        - "6789:6789" # Mobile speed tests
                        - "8080:8080" # Device controller communication
                        - "8443:8443" # Port used for controller GUI/API as seen in a web browser
                volumes:
                        - "unifi-data:/unifi"
