version: '2'
volumes:
        unifi-data:
        unms-data:
services:
        unifi:
                build: ./unifi
                ports:
                        # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
                        - "10001:10001/udp" # AP discovery 
                        - "3478:3478/udp" # STUN
                        - "6789:6789" # Mobile speed tests
                        - "8080:8080" # Device controller communication
                volumes:
                        - "unifi-data:/unifi"
        unms:
                build: ./unms
                volumes:
                        - "unms-data:/config"
